name: Build & Publish Latest

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - production

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        run: echo RELEASE=$(cat ./src/package.json | jq -r .release.version) >> $GITHUB_ENV

      # Build & Publish
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: mfominov/wg-easy:latest, mfominov/wg-easy:${{ env.RELEASE }}
