name: Build & Publish Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wg-easy'
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: mfominov/wg-easy:nightly
